### ISSUE TITLE
File named openapi.yaml not detected

### ISSUE THREAD

**Issue by baztian** [zalando/intellij-swagger#210] opened 2018-11-14 14:04 UTC
When I name my OpenAPI file `openapi.yml` the plugin autocompletion works. If I name it to the desired `openapi.yaml` it doesn't work.
In #146 there was a similar comment. Unfortunately the solution to create a new file with `openapi: 3.0.0`, closing it and reopening it doesn't work for me.

**Comment by semonte** [comment] 2018-11-15 06:21
Hi,

The filename _should_ not matter, for example the following works for me with version `1.0.19`:

![image](https://user-images.githubusercontent.com/1151536/48533962-2277d680-e8af-11e8-8daa-b7db16650e9e.png)

In order to debug this further, I would need to know which version of the plugin and IDE you are using.

**Comment by baztian** [comment] 2018-11-15 08:45
Thanks @semonte,
I tried creating a file named {{test.xaml}} and it worked as in your example. Then I switched back to my {{openapi.yaml}} file and the plugin started to work there too!

I don't know what caused the problem initially and what fixed it. I installed the plugin just yesterday after I already started editing the yaml file. I tried with restarting, renaming forth and back but without success.

I'm fine if you close this issue but I guess there is some small glitch in the plugin that in some situations causes it not to work properly.

**Comment by semonte** [comment] 2018-11-15 09:45
Thanks for the additional information. I'll check if I can reproduce this.

**Comment by semonte** [comment] 2018-12-10 06:48
@baztian the latest version the plugin provides icons for Swagger and OpenAPI files. If an icon is displayed, the plugin is active for that file. This should help in possible future issues regarding this. I'll close this issue, because there are no further actions for now.

**Closed as completed by semonte** 2018-12-10 06:49 UTC
