### ISSUE TITLE
Nothing happens when clicking Chrome icon for accessing Swagger UI

### ISSUE THREAD

**Issue by dodalovic** [zalando/intellij-swagger#231] opened 2019-02-09 12:34 UTC
IntelliJ IDEA 2018.3.4 (Ultimate Edition)
Build #IU-183.5429.30, built on January 29, 2019
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'content' of com/intellij/notification/Notification.<init> must not be null
	at com.intellij.notification.Notification.$$$reportNull$$$0(Notification.java)
	at com.intellij.notification.Notification.<init>(Notification.java)
	at org.zalando.intellij.swagger.service.SwaggerFileService.notifyFailure(SwaggerFileService.java:63)
	at org.zalando.intellij.swagger.service.SwaggerFileService.convertSwaggerToHtml(SwaggerFileService.java:36)
	at org.zalando.intellij.swagger.ui.provider.SwaggerUiUrlProvider.getUrl(SwaggerUiUrlProvider.java:32)
	at com.intellij.ide.browsers.WebBrowserUrlProvider.getUrls(WebBrowserUrlProvider.kt:33)
	at com.intellij.ide.browsers.impl.WebBrowserServiceImplKt.getUrls(WebBrowserServiceImpl.kt:81)
	at com.intellij.ide.browsers.impl.WebBrowserServiceImplKt.access$getUrls(WebBrowserServiceImpl.kt:1)
	at com.intellij.ide.browsers.impl.WebBrowserServiceImpl.getUrlsToOpen(WebBrowserServiceImpl.kt:59)
	at com.intellij.ide.browsers.actions.BaseOpenInBrowserActionKt.openInBrowser(BaseOpenInBrowserAction.kt:38)
	at com.intellij.ide.browsers.actions.BaseOpenInBrowserActionKt.openInBrowser(BaseOpenInBrowserAction.kt:57)
	at com.intellij.ide.browsers.actions.BaseOpenInBrowserAction.actionPerformed(BaseOpenInBrowserAction.kt:123)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:184)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:148)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:410)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by semonte** [comment] 2019-02-11 08:29
Duplicate of https://github.com/zalando/intellij-swagger/issues/230 . Version 1.0.24 will fix this, it is pending for JetBrains approval. Thanks for reporting anyway!

**Closed as completed by semonte** 2019-02-11 08:29 UTC
