### ISSUE TITLE
Cannot resolve ref for schemas in an another file 

### ISSUE THREAD

**Issue by kota65535** [zalando/intellij-swagger#312] opened 2020-06-19 06:49 UTC
Reference to a schema in an another file leads to the red line warning.

![image](https://user-images.githubusercontent.com/10975834/85104772-2ebed500-b244-11ea-9431-aac5bf9172dc.png)

- I can still  jump to the schema in the file by Navigate -> Goto. 
- Autocomplete (suggestion) does not work, neither.

![image](https://user-images.githubusercontent.com/10975834/85104827-48f8b300-b244-11ea-8dad-be890a79a978.png)

minimal reproduction respository is here:
https://github.com/kota65535/swagger-test

Thank you

**Comment by kota65535** [comment] 2020-06-20 03:51
Forgot to tell my environment:

- Intellij IDEA Ultimate: 2020.1.2
- Plugin version: 1.0.28

**Comment by hcomnetworkers** [comment] 2020-08-31 11:34
Should be a duplicate of #277

**Comment by tkrop** [comment] 2021-04-15 15:48
Acknowledged duplicate of #277. May be fixed by #307, however this has a political aspect that currently prevents merging. See https://github.com/zalando/intellij-swagger/pull/307#pullrequestreview-413347642.

**Closed as completed by tkrop** 2021-04-15 15:48 UTC
