### ISSUE TITLE
[Suggestion] provide an option to activate this plugin for arbitrary .yaml

### ISSUE THREAD

**Issue by taxpon** [zalando/intellij-swagger#41] opened 2016-06-21 03:34 UTC
### Problem

I am currently writing swagger spec in multiple files and combine them before I use the swagger spec as follows:

```
├── swagger.yaml
└── yaml
    ├── definitions
    │   ├── book.yaml
    │   └── user.yaml
    └── index.yaml
```

In this example, `swagger.yaml` is concatenated file of `book.yaml` , `user.yaml` and `index.yaml`. In `index.yaml` , "swagger" field exists so this plugin is activated, while I can not use this plugin in `book.yaml` and `user.yaml` because they do not have "swagger" field.
### Suggestion

Please provide optional comment to activate this plugin for files without swagger field as follows:

```
# intellij-swagger: activate
```

**Comment by semonte** [comment] 2016-06-24 06:25
Hi taxpon

Thanks for the suggestion, I have also thought about how referenced files should be handled. I think 
intellij-swagger should, in future, activate all files that are referenced by the main file.

However, this is not a small feature. The algorithm for finding what values are auto completed uses JSON/YAML path that is based on the main file structure. I will definitely implement this, but can not make any guarantees when.

**Comment by juan-quiver** [comment] 2016-08-16 19:26
+1

**Comment by semonte** [comment] 2016-09-26 08:38
Duplicate of https://github.com/zalando/intellij-swagger/issues/52

**Closed as completed by semonte** 2016-09-26 08:38 UTC
Labels: duplicate
