### ISSUE TITLE
Compatibility with IntelliJ EAP 2021.1

### ISSUE THREAD

**Issue by Lauri-Nomme** [zalando/intellij-swagger#318] opened 2021-02-01 13:25 UTC
Opening any swagger description file results in
```
com.intellij.diagnostic.PluginException: Cannot create class org.zalando.intellij.swagger.inspection.reference.JsonReferenceInspection (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Swagger, id=org.zalando.intellij.swagger, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2021.1\plugins\intellij-swagger, version=1.0.28, package=null), packagePrefix=null, instanceId=191, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:763)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:781)
	at com.intellij.serviceContainer.LazyExtensionInstance.createInstance(LazyExtensionInstance.java:54)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.createInstance(CustomLoadingExtensionPointBean.java:29)
	at com.intellij.codeInspection.InspectionEP.instantiateTool(InspectionEP.java:206)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getTool(InspectionToolWrapper.java:80)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.getInspectionTools(LocalInspectionsPass.java:769)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:115)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1114)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:612)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:181)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NoSuchMethodException: org.zalando.intellij.swagger.inspection.reference.JsonReferenceInspection.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:720)
	... 26 more```

**Comment by freeedrik** [comment] 2021-04-07 08:18
Intelij 2021.1 is now the latest stable version if running the snap on Ubuntu. So today it stopped working for me.

**Comment by radarsh** [comment] 2021-04-07 15:09
MacOS IntelliJ IDEA Ultimate - this plugin repeatedly crashes with the above stack trace and gradually eats into the allocated memory for IntelliJ.

**Comment by lhasselb** [comment] 2021-04-08 07:02
Win10 IntelliJ IDEA Ultimate - plugin stopped working after update to 21.1.

**Comment by shaundsmith** [comment] 2021-04-08 08:39
I'm seeing a similar issue in the logs on Max OS with IntelliJ ultimate 2021.1.

The error seems to prevent code completion/inspection from working in non-swagger files too. Disabling the plugin resolves the issues with code completion/inspection.

**Comment by marcelstoer** [comment] 2021-04-09 19:26
Seeing the same stacktrace upon opening any (Java) project in IntelliJ 2021.1. It troubles me as it appears this fine plugin is now unmaintained. @tkrop @zeitlinger can you reproduce this?

Looks like https://github.com/zalando/intellij-swagger/blob/master/src/main/java/org/zalando/intellij/swagger/inspection/reference/JsonReferenceInspection.java#L18 is missing a default constructor.

**Comment by tvolkov** [comment] 2021-04-13 17:20
seeing the same issue with crashing plugin on m1 mac
without disabling it the [code editor' color scheme gets mad](https://youtrack.jetbrains.com/issue/IDEA-266727) which is pretty weird

**Comment by zeitlinger** [comment] 2021-04-14 13:10
I've just looked into this issue - and plugin development in general...

Therefore, I'm a bit more conservative and have uploaded the new plugin to the beta channel:

https://plugins.jetbrains.com/plugin/8347-swagger/versions/beta/117026

Once someone has confirmed it's working, I'll publish to the main channel.

**Comment by honzabazant** [comment] 2021-04-14 14:03
Tested.
- Code completion works for me
- Analysis works correctly (e.g. if I reference a non-existent element in $ref, it is correctly reported as error)

However I noticed two issues, but these are not major for me and I can easily live with them.

So now I want to thank you for making this plugin great again 😄 

- When IDE starts and the plugin loads, the following exception is reported (clearly it has something to do with custom icons for OpenAPI files):
`java.lang.NullPointerException
	at org.zalando.intellij.swagger.file.icon.SpecIconProvider.getIcon(SpecIconProvider.java:27)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:17)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:37)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:222)
	at com.intellij.util.IconUtil.computeFileIcon(IconUtil.java:155)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.lambda$updateFileIconAsynchronously$7(EditorsSplitters.java:419)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:119)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

- When I try to open the API specification in browser using the toolbar shown near the upper right corner (shown on mouse move), nothing happens and the following error is reported:
`java.lang.IllegalArgumentException: Argument for @NotNull parameter 'content' of com/intellij/notification/Notification.<init> must not be null
	at com.intellij.notification.Notification.$$$reportNull$$$0(Notification.java)
	at com.intellij.notification.Notification.<init>(Notification.java)
	at org.zalando.intellij.swagger.service.SwaggerFileService.notifyFailure(SwaggerFileService.java:65)
	at org.zalando.intellij.swagger.service.SwaggerFileService.convertSwaggerToHtml(SwaggerFileService.java:37)
	at org.zalando.intellij.swagger.ui.provider.SwaggerUiUrlProvider.getUrl(SwaggerUiUrlProvider.java:33)
	at com.intellij.ide.browsers.WebBrowserUrlProvider.getUrls(WebBrowserUrlProvider.kt:33)
	at com.intellij.ide.browsers.impl.WebBrowserServiceImplKt.getUrls(WebBrowserServiceImpl.kt:77)
	at com.intellij.ide.browsers.impl.WebBrowserServiceImplKt.access$getUrls(WebBrowserServiceImpl.kt:1)
	at com.intellij.ide.browsers.impl.WebBrowserServiceImpl.getUrlsToOpen(WebBrowserServiceImpl.kt:55)
	at com.intellij.ide.browsers.actions.BaseOpenInBrowserAction$Companion.openInBrowser$intellij_platform_ide_impl(BaseOpenInBrowserAction.kt:42)
	at com.intellij.ide.browsers.actions.BaseOpenInBrowserAction$Companion.openInBrowser$intellij_platform_ide_impl(BaseOpenInBrowserAction.kt:61)
	at com.intellij.ide.browsers.actions.BaseOpenInBrowserAction.actionPerformed(BaseOpenInBrowserAction.kt:119)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:273)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:273)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:201)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:174)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:157)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:470)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`

**Comment by revilwang** [comment] 2021-04-19 11:20
After installing the beta version, auto-completion is working, but an error still pops out, which is the same with the first case described in @honzabazant 's comment. Still I can live with the error. Thanks for the work.

**Comment by mojorero** [comment] 2021-04-23 16:27
FYI. Editor inspections not working after updating to IntelliJ 2021.1.

Extracted from the following ticket https://github.com/zalando/intellij-swagger/issues/325

Today I updated IntelliJ IDEA to the version 2021.1.

After that, the editor inspections did not work anymore (at least with Gradle and Maven projects with Java code). The inspections seen in the project explorer did work though.

Deinstalling the Plugin for Swagger helps. I was not able to find a better solution which allows me to keep using the Swagger Plugin.

After reinstalling the plugin again, I get this error:
![image](https://user-images.githubusercontent.com/11564614/115901470-867c2d00-a461-11eb-9e08-26a8fa4224ce.png)
Here is the information from the 'about IntelliJ' panel

IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4933M
Cores: 8
Non-Bundled Plugins: com.jetbrains.ChooseRuntime (1.2), org.sonarlint.idea (4.14.2.28348), aws.toolkit (1.26-211), org.jetbrains.kotlin (211-1.4.32-release-IJ6693.72), com.intellij.selenium (211.6693.108)
Kotlin: 211-1.4.32-release-IJ6693.72

**Comment by ye** [comment] 2021-05-05 23:47
While waiting for the compatibility issues to be resolved and merged to to be released there are 2 alternatives:

1. JetBrains has released their own plugin for OpenAPI - https://plugins.jetbrains.com/plugin/14394-openapi-specifications
2. Insomnia as a stand alone API spec design tool / OpenAPI renderer https://github.com/Kong/insomnia

**Comment by ye** [comment] 2021-05-25 16:05
> I've just looked into this issue - and plugin development in general...
> 
> Therefore, I'm a bit more conservative and have uploaded the new plugin to the beta channel:
> 
> https://plugins.jetbrains.com/plugin/8347-swagger/versions/beta/117026
> 
> Once someone has confirmed it's working, I'll publish to the main channel.

So I removed the old Swagger plugin stable version 1.0.28 and then disabled the JetBrains OpenAPI plugin, and then downloaded the above beta version (Swagger beta 1.1) to disk and installed it from disk. The problem still persist and I am seeing it crashing and popup a Java stack trace immediate after trying to open the old OpenAPI YAML file.

I am running 
 ```
PyCharm 2021.1.1 (Professional Edition)
Build #PY-211.7142.13, built on April 21, 2021
Runtime version: 11.0.10+9-b1341.41 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS Big Sur 11.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
```

<img width="1385" alt="Screen Shot 2021-05-25 at 12 01 06 PM" src="https://user-images.githubusercontent.com/133924/119531017-8a95b600-bd51-11eb-9d7d-91c9f4591b5d.png">

and this error
<img width="1389" alt="Screen Shot 2021-05-25 at 12 10 27 PM" src="https://user-images.githubusercontent.com/133924/119531795-47881280-bd52-11eb-9c75-7396c5b82070.png">

**Comment by Spurlos** [comment] 2021-06-14 20:24
Plugin throws Exception mentioned above on each start and actions in IDE :|

**Comment by sambaranhazra** [comment] 2021-07-08 06:56
Hi @Spurlos and @ye ,

Can you please try with the version [1.1.1](https://plugins.jetbrains.com/plugin/8347-swagger/versions/beta/126353) from beta channel?

**Closed as completed** 2021-07-08 14:06 UTC

**Comment by ye** [comment] 2021-07-21 04:43
@sambaranhazra yes I can confirm that [stable version 1.1.1](https://plugins.jetbrains.com/plugin/8347-swagger/versions/stable/126722) is working now on the current latest PyCharm. Thank you!

```
PyCharm 2021.1.3 (Professional Edition)
Build #PY-211.7628.24, built on June 30, 2021
Runtime version: 11.0.11+9-b1341.60 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
Non-Bundled Plugins: ideanginx9 (0.1.9), com.intellij.kubernetes (211.7442.27), org.zalando.intellij.swagger (1.1.1), org.toml.lang (0.2.151.3997-211), com.intellij.swagger (211.7142.14), ru.meanmail.plugin.requirements (2021.4-211)
```

> Hi @Spurlos and @ye ,

> Can you please try with the version 1.1.1 from beta channel?
